version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"       # External 3000 → Internal Nginx port 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
